services:
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_US-lessac-medium # Default voice
      - PIPER_VOICES_DIR=/voices
      - LANG=C.UTF-8 # <--- ADD THIS LINE
    volumes:
      - ./piper_voices:/voices
    ports:
      - "5001:5000"
    restart: unless-stopped
    dns:
      - 8.8.8.8

  bot:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "host" 
    command: python -m tele_notebook.bot.main
    env_file:
      - .env
    # --- ADD THIS BLOCK ---
    # environment:
    #   - HTTP_PROXY=http://57.129.81.201:8080 #4.149.210.210:3128
    #   - HTTPS_PROXY=http://57.129.81.201:8080
    #   - NO_PROXY=localhost,127.0.0.1,redis,piper #,api.telegram.org
    # ----------------------
    volumes:
      - ./tele_notebook:/app/tele_notebook
      - ./chroma_data:/app/chroma_data
      - uploads_volume:/app/uploads
    depends_on:
      - redis
      - piper

  worker:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "host" 
    command: celery -A tele_notebook.tasks.celery_app worker --loglevel=info -P solo
    env_file:
      - .env
    # --- ADD THIS BLOCK ---
    # environment:
    #   - HTTP_PROXY=http://57.129.81.201:8080
    #   - HTTPS_PROXY=http://57.129.81.201:8080
    #   - NO_PROXY=localhost,127.0.0.1,redis,piper #,api.telegram.org
    # ----------------------
    volumes:
      - ./tele_notebook:/app/tele_notebook
      - ./chroma_data:/app/chroma_data
      - uploads_volume:/app/uploads
    depends_on:
      - redis
      - piper
      - bot

volumes:
  redis_data:
  piper_voices:
  uploads_volume: