services:
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  bot:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # network_mode: "host"  <--- REMOVE THIS LINE
    command: python -m tele_notebook.bot.main
    env_file:
      - .env
    volumes:
      - ./tele_notebook:/app/tele_notebook
      - ./chroma_data:/app/chroma_data
      - uploads_volume:/app/uploads
    depends_on:
      - redis

  worker:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # network_mode: "host"  <--- REMOVE THIS LINE
    command: celery -A tele_notebook.tasks.celery_app worker --loglevel=info -P solo
    env_file:
      - .env
    volumes:
      - ./tele_notebook:/app/tele_notebook
      - ./chroma_data:/app/chroma_data
      - uploads_volume:/app/uploads
    depends_on:
      - redis
      - bot

volumes:
  redis_data:
  uploads_volume: